version: '3.6'

services:

  #services:
  #  portainer:
  #    image: portainer/portainer
  #    ports:
  #    - "9000:9000"
  #    command: -H unix:///var/run/docker.sock
  #    volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #    - portainer_data:/data
  #volumes:
  #  portainer_data:

  elevator-client:
    image: elevator-client:latest
    build:
     context: ./services/fasta-client
     dockerfile: Dockerfile-dev
    restart: on-failure
    volumes:
     - '/home/parot/eva-dev/mnt/logs/elevator:/usr/src/app/logs/elevator/'
    # - './services/fasta-client:/usr/src/app'
    environment:
     - API_TYPE=elevator
     - APP_SETTINGS=project.config.DevelopmentConfig
     - MONGO_URI=mongodb://bart:downy37)tory@mongo-db:27017/eva_dev
     - FASTA_URL=https://api.deutschebahn.com/fasta/v2/facilities?type=ELEVATOR
     - LOG_DIR=./logs/elevator/
    depends_on:
     - mongo-db

  escalator-client:
    image: escalator-client:latest
    build:
     context: ./services/fasta-client
     dockerfile: Dockerfile-dev
    restart: on-failure
    volumes:
     - '/home/parot/eva-dev/mnt/logs/escalator:/usr/src/app/logs/escalator/'
    # - './services/fasta-client:/usr/src/app'
    environment:
     - API_TYPE=escalator
     - APP_SETTINGS=project.config.DevelopmentConfig
     - MONGO_URI=mongodb://bart:downy37)tory@mongo-db:27017/eva_dev
     - FASTA_URL=https://api.deutschebahn.com/fasta/v2/facilities?type=ESCALATOR
     - LOG_DIR=./logs/escalator/
    depends_on:
     - mongo-db

  db-api:
    image: db-api:latest
    build:
      context: ./services/db-api
      dockerfile: Dockerfile-dev
      #command: python -u app.py
    restart: on-failure
    volumes:
      - './services/db-api:/usr/src/app'
    #  - '/etc/group:/etc/group:ro'
    #  - '/etc/passwd:/etc/passwd:ro'
    ports:
      - "5001:5000"
    environment:
     - FLASK_APP=project/__init__.py
     - FLASK_ENV=development
     - APP_SETTINGS=project.config.DevelopmentConfig
     - POSTGRES_URL=postgres://postgres:postgres@station-db:5432/eva_dev
     - MASTER_STATION=./project/db/db-stations.csv
     - MASTER_ELEVATOR=./project/db/db-elevator.csv
     - MONGO_URI=mongodb://bart:downy37)tory@mongo-db:27017/eva_dev
    depends_on:
      - station-db
    deploy:
      replicas: 1
     # resources:
     #   limits:
     #     cpus: "0.1"#
     #     memory: 50M
      restart_policy:
        condition: on-failure

# Databases

  station-db:
    image: station-db:latest
    build:
      context: ./services/db-api/project/db
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  mongo-db:
    image: mongo:latest
    command: mongod --port 27017
    restart: unless-stopped
    ports:
      - "27027:27017"
      - "28028:28018"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bart
      - MONGO_INITDB_ROOT_PASSWORD=downy37)tory
    volumes:
      - '/home/parot/eva-dev/mnt/mongo/data/configdb:/data/configdb'
      - '/home/parot/eva-dev/mnt/mongo/data:/data/db'
      #- '/etc/group:/etc/group:ro'
      #- '/etc/passwd:/etc/passwd:ro'
    deploy:
      replicas: 1
      # resources:
      #   limits:
      #     cpus: "0.1"#
      #     memory: 50M
      restart_policy:
        condition: on-failure

  # Dashboard
  dashboard-server:
    image: dashboard:latest
    build:
      context: ./services/dashboard
      dockerfile: Dockerfile-dev
      #command: python -u app.py
    restart: on-failure
    volumes:
      - './services/dashboard:/usr/src/app'
    #  - '/etc/group:/etc/group:ro'#
    #  - '/etc/passwd:/etc/passwd:ro'
    ports:
     - "37002:37002"
    environment:
     - APP_SETTINGS=project.config.DevelopmentConfig
     - POSTGRES_URL=postgresql://postgres:postgres@station-db:5432/eva_dev
     - MONGO_URI=mongodb://bart:downy37)tory@mongo-db:27017/eva_dev
    depends_on:
      - station-db
      - mongo-db

